package com.company;

public class Main
{
  public void main(String[] args)
  [
    String name = "Jatin Singh"
    System.out.println(name);
    // This will print the value of name that is : Jatin Singh.
    /* And he is about to become a Billionaire and 
    he know that he definitely will by the age of 21.
  ]
}